//@host = https://old-fog-2691.fly.dev 
@host=http://localhost:3000

GET {{host}}

###

POST {{host}}/profile
Content-Type: application/json

{
    "username": "suraj",
    "password": "suraj1294"
}

