version: "3.1"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: suraj
      POSTGRES_DB: postgres
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 5432:5432
