# fly.toml app configuration file generated for shy-paper-548 on 2023-09-18T14:23:14+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-paper-548"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
